config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }
  root to: 'roasts#index'

  resources :roasts do
    resources :brews do
    end
  end

  resources :users do
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brew.rb
# == Schema Information
#
# Table name: brews
#
#  id           :integer          not null, primary key
#  roast_id     :integer
#  brew_method  :string
#  time_of_brew :datetime
#  qty_of_beans :integer
#  bitterness   :integer
#  complexity   :integer
#  acidity      :integer
#  overall      :integer
#  texture      :string
#  comments     :text
#  user_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  date_of_brew :datetime
#

class Brew < ApplicationRecord

  belongs_to :roast
  belongs_to :user

  validates	:brew_method,				presence: true
  validates	:date_of_brew,			presence: true
  validates	:overall, 	        presence: true

end

app/models/roast.rb
# == Schema Information
#
# Table name: roasts
#
#  id                  :integer          not null, primary key
#  roast_method        :string
#  date_of_roast       :datetime
#  bean_species        :string
#  roast_duration      :integer
#  time_of_roast       :datetime
#  roast_profile       :string
#  avg_temp_roast      :integer
#  raw_weight          :integer
#  storage             :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  user_id             :integer
#  bean_country_origin :string
#  bean_varietal_name  :string
#

class Roast < ApplicationRecord
	has_many :brews

	validates	:roast_method,				presence: true
	validates	:date_of_roast,				presence: true
	validates	:bean_species,				presence: true
	validates	:roast_duration,			presence: true
	validates	:time_of_roast,				presence: true
	validates	:roast_profile,				presence: true
	validates	:avg_temp_roast,			presence: true
	validates	:raw_weight,					presence: true
	validates	:bean_country_origin,	presence: true
	validates	:bean_varietal_name, 	presence: true

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default("")
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  user_type_id           :integer
#  first_name             :string
#  last_name              :string
#  provider               :string
#  uid                    :string
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :omniauthable, :omniauth_providers => [:facebook]

  belongs_to :user_type
  has_many :brews
  before_validation :assign_user_type # Assign users as standard
  validates_uniqueness_of :email # is allowed to be nil, because new user will using omniAuth
  validates_uniqueness_of :uid, scope: [:provider] # Ensure unique oauth uid from providers

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.nickname = auth.info.name
      user.picture = auth.info.image
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end

  def assign_user_type
    self.user_type = UserType.find_by(name: "Standard")
  end
end

app/models/user_type.rb
# == Schema Information
#
# Table name: user_types
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class UserType < ApplicationRecord
	has_many :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/brews_controller.rb
class BrewsController < ApplicationController

  def index
    @brews = roast.brews
  end

  def show
    roast
    @brew = Brew.find(params[:id]).decorate
  end

  def new
    @roast = roast
    @brew = Brew.new
  end

  def edit
    @roast = roast
    @brew = Brew.find(params[:id])
  end


  def create
  	@brew = Brew.new(brew_params)
  	@brew.user_id = current_user.id
    @brew.roast_id = roast.id
  	if @brew.save
  		redirect_to [roast, @brew], notice: "Your review was successfully saved!"
  	else
  		render :new
  	end
  end

  def update
    @brew = Brew.find(params[:id])
    @roast = roast
    if @brew.update(brew_params)
      redirect_to [roast, @brew], notice: "Your review was successfully saved!"
    else
      render :edit
    end
  end

  private

  def roast
    @roast ||= Roast.find(params[:roast_id]).decorate
  end

  def brew_params
    params.require(:brew).permit(
      :brew_method,
      :date_of_brew,
      :qty_of_beans,
      :time_of_brew,
      :texture,
      :acidity,
      :bitterness,
      :complexity,
      :comments,
      :overall
      )
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
      generic_callback( 'facebook' )
  end

  def generic_callback( provider )
    @user = User.from_omniauth(request.env['omniauth.auth'])
    if @user.persisted?
      set_flash_message(:notice, :success, kind: provider.capitalize) if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/registrations_controller.rb
# extends devise to persist first_name/last_name on signup
class RegistrationsController < Devise::RegistrationsController


	private
		def sign_up_params
			params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
		end

		def account_update_params
			params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
		end
end

app/controllers/roasts_controller.rb
class RoastsController < ApplicationController
	before_action :authenticate_user!

  def index
  	@roasts = Roast.all.decorate
  end

  def new
  	@roast = Roast.new
  end

	def edit
		@roast = Roast.find(params[:id])
	end

  def create
  	@roast = Roast.new(roast_params)
  	@roast.user_id = current_user.id
  	if @roast.save
  		redirect_to @roast, notice: "Your Roast was successfully saved!"
  	else
  		render :new
  	end
  end

	def update
		@roast = Roast.find(params[:id])
		if @roast.update(roast_params)
			redirect_to @roast, notice: "Your Roast was successfully saved!"
		else
			render :edit
		end
	end

  def show
		@raw_roast = Roast.find(params[:id])
  	@roast = @raw_roast.decorate
  end

  private

	def roast_params
		params.require(:roast).permit(
			:roast_method,
			:date_of_roast,
			:bean_species,
			:bean_country_origin,
			:bean_varietal_name,
			:roast_duration,
			:time_of_roast,
			:roast_profile,
			:avg_temp_roast,
			:raw_weight,
			:storage
			)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @brews = Brew.where(user_id: current_user.id).decorate
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/roasts_helper.rb
module RoastsHelper
end

app/views/brew/index.html.erb
<div class='container'>
	<h1>Brews</h1>
<hr>

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<table class="table table-hover table-bordered">
				<thead>
					<tr>
            <th>Roast Batch #</th>
						<th>#</th>
						<th>
							Brew Method
						</th>
						<th>
							Date of Brew
						</th>
						<th>
							Quantity of Beans (grams)
						</th>
						<th>
							Overall
						</th>
						<th>
							view more...
						</th>
					</tr>
				</thead>

				<tbody>
					<% @brews.each do |brew| %>
					<tr>
            <td><%= @roast.id %></td>
						<td><%= brew.id %></td>
						<td><%= brew.formatted_brew_method %></td>
						<td><%= brew.formatted_time_of_brew %></td>
						<td><%= brew.formatted_qty_of_beans %></td>
						<td><%= brew.formatted_overall %></td>
						<td><%= link_to'view',roast_brew_path(@roast.id, brew.id), class: 'btn btn-success' %></td>
					</tr>
					<% end %>
				</tbody>
			</table>

			<%= link_to 'Back to Roast', roast_path(@roast.id), class: 'btn btn-info' %>
		</div>
	</div>
</div>

app/views/brews/_form.html.erb
<%= form_for [@roast,@brew], html: {class: 'form-horizontal'} do |f| %>
  <%= render 'shared/error_messages', obj: @brew %>

  <div class='row col-md-12'>
    <div class="col-md-5 center-block">
      <div class="form-group">
        <%= f.label :brew_method %>
        <%= f.text_field :brew_method, class: 'form-control' %>
     </div>
    </div>
  </div>

  <div class="row col-md-12">
    <div class='col-md-3 form-group'>
      <%= f.label :date_of_brew %>
      <div class="input-group date" id="datepicker">
        <%= f.text_field :date_of_brew, autocomplete: 'off', class: 'form-control' %>
        <span class="input-group-addon">
          <span class="glyphicon glyphicon-time"></span>
        </span>
      </div>
    </div>

    <div class="col-md-3 form-group">
      <%= f.label :time_of_brew %>
      <div class='input-group date' id='timepicker'>
        <%= f.text_field :time_of_brew, autocomplete: 'off', class: 'form-control' %>
        <span class="input-group-addon">
          <span class="glyphicon glyphicon-time"></span>
        </span>
      </div>
    </div>

    <div class="col-md-6 form-group">
      <%= f.label :qty_of_beans %>
      <%= f.text_field :qty_of_beans, class: 'form-control', placeholder: "(grams)"  %>
    </div>
    <div class="col-md-6 form-group">
      <%= f.label :texture %>
      <%= f.text_field :texture, class: 'form-control', placeholder: "ex: full-bodied"  %>
    </div>

  </div>

  <div class="row col-md-12">
    <div class="col-md-4 form-group">
      <%= f.label :bitterness %>
      <%= f.text_field :bitterness, class: 'form-control', placeholder: "(1-10)" %>
    </div>

    <div class="col-md-4 form-group">
      <%= f.label :acidity %>
      <%= f.text_field :acidity, class: 'form-control', placeholder: "(1-10)" %>
    </div>

    <div class="col-md-4 form-group">
      <%= f.label :complexity %>
      <%= f.text_field :complexity, class: 'form-control', placeholder: "(1-10)" %>
    </div>

    <div class="col-md-4 form-group">
      <%= f.label :overall %>
      <%= f.text_field :overall, class: 'form-control', placeholder: "(1-10)" %>
    </div>

    <div class="col-md-4 form-group">
      <%= f.label :comments %>
      <%= f.text_area :comments, class: 'form-control', placeholder: "Misc. Comments" %>
    </div>
  </div>

  <div class="row col-md-12">
    <%= f.submit 'Save Brew', class: 'btn btn-coffee' %>
    <%= link_to'Cancel', :back, class: 'btn btn-coffee2' %>
  </div>
<% end %>


<%# target date_of_roast text_field for Bootstrap datepicker %>
<%= javascript_tag do %>
$('#timepicker').datetimepicker({format: 'LT'});
$('#datepicker').datetimepicker({format: 'YYYY/MM/DD'});
<% end %>

app/views/brews/edit.html.erb
<h1> Edit Brew</h1>

<%= render 'form' %>

app/views/brews/index.html.erb
<div class='container'>
	<h1>Brews</h1>
<hr>

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<table class="table table-hover table-bordered">
				<thead>
					<tr>
            <th>Roast Batch #</th>
						<th>#</th>
						<th>
							Brew Method
						</th>
						<th>
							Date of Brew
						</th>
						<th>
							Quantity of Beans (grams)
						</th>
						<th>
							Overall
						</th>
						<th>
							view more...
						</th>
					</tr>
				</thead>

				<tbody>
					<% @brews.each do |brew| %>
					<tr>
            <td><%= @roast.id %></td>
						<td><%= brew.id %></td>
						<td><%= brew.formatted_brew_method %></td>
						<td><%= brew.formatted_time_of_brew %></td>
						<td><%= brew.formatted_qty_of_beans %></td>
						<td><%= brew.formatted_brew_overall %></td>
						<td><%= link_to'view',roast_brew_path(@roast.id, brew.id), class: 'btn btn-success' %></td>
					</tr>
					<% end %>
				</tbody>
			</table>

			<%= link_to 'Back to Roast', roast_path(@roast.id), class: 'btn btn-info' %>
			<%= link_to 'Create Brew', new_roast_brew_path(@roast.id), class: 'btn btn-success' %>
		</div>
	</div>
</div>

app/views/brews/new.html.erb
<h1> New Brew</h1>

<%= render 'form' %>

app/views/brews/show.html.erb
<div class='roast-show-wrapper'>
  <div class='left-text'>

    <div>
      <h3>Brew Method:</h3><%= @brew.formatted_brew_method %>
    </div>
    <div class='roast-data'>
      <div class='roast-data-col'>
        <div>
          <h3>Date of Brew:</h3><%= @brew.formatted_date_of_brew %>
        </div>
        <div>
          <h3>Time of Brew:</h3><%= @brew.formatted_time_of_brew %>
        </div>
        <div>
          <h3>Qty of Beans:</h3><%= @brew.formatted_qty_of_beans %>
        </div>
        <div>
          <h3>Texture:</h3><%= @brew.formatted_brew_texture %>
        </div>
      </div>
      <div class='roast-data-col'>
        <div>
          <h3>Acidity:</h3><%= @brew.formatted_brew_acidity %>
        </div>
        <div>
          <h3>Bitterness:</h3><%= @brew.formatted_brew_bitterness %>
        </div>
        <div>
          <h3>Complexity:</h3><%= @brew.formatted_brew_complexity %>
        </div>
        <div>
          <h3>Overall:</h3><%= @brew.formatted_brew_overall %>
        </div>
        <div>
          <h3>Comments:</h3><%= @brew.formatted_brew_comments %>
        </div>
      </div>
    </div>

    <div>
      <%= link_to"All Roasts", root_path, class: 'btn btn-success' %>
      <%= link_to "All Brews", roast_brews_path(@roast.id), class: 'btn btn-info' %>
      <%= link_to 'Edit', edit_roast_brew_path(@roast.id, @brew.id), class: 'btn btn-coffee2' %>
    </div>
  </div>

  <div class='charts'>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Roastdata</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
      <div class="row">
          <%= render 'shared/nav' %>
          <%= render 'shared/alerts' %>
    	    <%= yield %>
    </div>
  </body>
</html>

app/views/roast/index.html.erb
<div class='container'>
	<h1>Roasts</h1>
<hr>

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<table class="table table-hover table-bordered">
				<thead>
					<tr>
						<th>#</th>
						<th>
							Roast Method
						</th>
						<th>
							Date of Roast
						</th>
						<th>
							Bean Species
						</th>
						<th>
							Roast Duration
						</th>
						<th>
							view more...
						</th>
					</tr>
				</thead>

				<tbody>
					<% @roasts.each do |roast| %>
					<tr>
						<td><%= roast.id %></td>
						<td><%= roast.roast_method %></td>
						<td><%= roast.date_of_roast.to_date %></td>
						<td><%= roast.bean_species %></td>
						<td><%= roast.formatted_roast_time %></td>
						<td><%= link_to'view',roast_path(roast.id), class: 'btn btn-success' %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/roasts/_form.html.erb
<%= form_for @roast, html: {class: 'form-horizontal'} do |f| %>
  <%= render 'shared/error_messages', obj: @roast %>

  <div class='row col-md-12'>
    <div class="col-md-5 center-block">
      <div class="form-group">
        <%= f.label :Roast_method %>
        <%= f.text_field :roast_method, class: 'form-control' %>
     </div>
    </div>
  </div>

  <div class="row col-md-12">
    <div class='col-md-3 form-group'>
      <%= f.label :Date_of_roast %>
      <div class="input-group date" id="datepicker">
        <%= f.text_field :date_of_roast, autocomplete: 'off', class: 'form-control' %>
        <span class="input-group-addon">
          <span class="glyphicon glyphicon-time"></span>
        </span>
      </div>
    </div>

    <div class="col-md-3 form-group">
      <%= f.label :Time_of_roast %>
      <div class='input-group date' id='timepicker'>
        <%= f.text_field :time_of_roast, autocomplete: 'off', class: 'form-control' %>
        <span class="input-group-addon">
          <span class="glyphicon glyphicon-time"></span>
        </span>
      </div>
    </div>

    <div class="col-md-6 form-group">
      <%= f.label :bean_species %>
      <%= f.text_field :bean_species, class: 'form-control', placeholder: "ex: Arabica"  %>
    </div>
    <div class="col-md-6 form-group">
      <%= f.label :Bean_country_origin %>
      <%= f.text_field :bean_country_origin, class: 'form-control', placeholder: "ex: Sumatra"  %>
    </div>
    <div class="col-md-6 form-group">
      <%= f.label :bean_varietal_name %>
      <%= f.text_field :bean_varietal_name, class: 'form-control', placeholder: "ex: Blue Thunder"  %>
    </div>

  </div><!-- end row 2 -->

  <div class="row col-md-12">
    <div class='col-md-6 form-group'>
        <div id='timepicker'>
          <%= f.label :roast_duration %>
          <%= f.text_field :roast_duration, class: 'form-control', placeholder: '(Seconds)' %>
        </div>
    </div>

    <div class="col-md-6 form-group">
      <%= f.label :Roast_profile %>
      <%= f.select :roast_profile,['Light', 'Medium', 'Meduim-dark', 'Dark'], {include_blank: true}, class: 'form-control' %>
    </div>
  </div>

  <div class="row col-md-12">
    <div class="col-md-4 form-group">
      <%= f.label :Average_temperature_of_roast %>
      <%= f.text_field :avg_temp_roast, class: 'form-control' %>
    </div>

    <div class="col-md-4 form-group">
      <%= f.label :Raw_bean_weight %>
      <%= f.text_field :raw_weight, class: 'form-control', placeholder: "(Grams)" %>
    </div>

    <div class="col-md-4 form-group">
      <%= f.label :Storage_method_of_beans %>
      <%= f.text_field :storage, class: 'form-control' %>
    </div>
  </div>

  <div class="row col-md-12">
    <%= f.submit 'Save Roast', class: 'btn btn-coffee' %>
    <%= link_to'Cancel', root_path, class: 'btn btn-coffee2' %>
  </div>
<% end %>


<%# target date_of_roast text_field for Bootstrap datepicker %>
<%= javascript_tag do %>
$('#timepicker').datetimepicker({format: 'LT'});
$('#datepicker').datetimepicker({format: 'YYYY/MM/DD'});
<% end %>

app/views/roasts/edit.html.erb
<h1> Edit Roast</h1>

<%= render 'form' %>

app/views/roasts/index.html.erb
<div class='container'>
	<h1>Roasts</h1>
<hr>

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<table class="table table-hover table-bordered">
				<thead>
					<tr>
						<th>#</th>
						<th>
							Roast Method
						</th>
						<th>
							Date of Roast
						</th>
						<th>
							Bean Species
						</th>
						<th>
							Roast Duration
						</th>
						<th>
							view more...
						</th>
					</tr>
				</thead>

				<tbody>
					<% @roasts.each do |roast| %>
					<tr>
						<td><%= roast.id %></td>
						<td><%= roast.roast_method %></td>
						<td><%= roast.roast_date %></td>
						<td><%= roast.bean_species %></td>
						<td><%= roast.formatted_roast_duration %></td>
						<td><%= link_to'view',roast_path(roast.id), class: 'btn btn-success' %></td>
					</tr>
					<% end %>
				</tbody>
			</table>

			<%= link_to'Create new Roast', new_roast_path, class: 'btn btn-success' %>
		</div>
	</div>
</div>

app/views/roasts/new.html.erb
<h1> New Roast</h1>

	<%= form_for @roast, html: {class: 'form-horizontal'} do |f| %>
	<%= render 'shared/error_messages', obj: @roast %>

	<div class='row col-md-12'>
		<div class="col-md-5 center-block">
			<div class="form-group">
			  <%= f.label :Roast_method %>
			  <%= f.text_field :roast_method, class: 'form-control' %>
		 </div>
		</div>
	</div>

	<div class="row col-md-12">
		<div class='col-md-3 form-group'>
			<%= f.label :Date_of_roast %>
			<div class="input-group date" id="datepicker">
				<%= f.text_field :date_of_roast, autocomplete: 'off', class: 'form-control', placeholder: 'dd/mm/yyyy' %>
				<span class="input-group-addon">
					<span class="glyphicon glyphicon-time"></span>
		    </span>
			</div>
		</div>

		<div class="col-md-3 form-group">
			<%= f.label :Time_of_roast %>
			<div class='input-group date' id='timepicker'>
				<%= f.text_field :time_of_roast, autocomplete: 'off', class: 'form-control' %>
				<span class="input-group-addon">
					<span class="glyphicon glyphicon-time"></span>
				</span>
			</div>
		</div>

	  <div class="col-md-6 form-group">
		  <%= f.label :bean_species %>
			<%= f.text_field :bean_species, class: 'form-control', placeholder: "ex: Arabica"  %>
	  </div>
		<div class="col-md-6 form-group">
			<%= f.label :Bean_country_origin %>
			<%= f.text_field :bean_country_origin, class: 'form-control', placeholder: "ex: Sumatra"  %>
		</div>
		<div class="col-md-6 form-group">
			<%= f.label :bean_varietal_name %>
			<%= f.text_field :bean_varietal_name, class: 'form-control', placeholder: "ex: Blue Thunder"  %>
		</div>

  </div><!-- end row 2 -->

  <div class="row col-md-12">
	  <div class='col-md-6 form-group'>
				<div id='timepicker'>
					<%= f.label :roast_duration %>
					<%= f.text_field :roast_duration, class: 'form-control', placeholder: '(Seconds)' %>
				</div>
		</div>

		<div class="col-md-6 form-group">
			<%= f.label :Roast_profile %>
			<%= f.select :roast_profile,['Light', 'Medium', 'Meduim-dark', 'Dark'], {include_blank: true}, class: 'form-control' %>
		</div>
	</div>

	<div class="row col-md-12">
		<div class="col-md-4 form-group">
			<%= f.label :Average_temperature_of_roast %>
			<%= f.text_field :avg_temp_roast, class: 'form-control' %>
		</div>

		<div class="col-md-4 form-group">
			<%= f.label :Raw_bean_weight %>
			<%= f.text_field :raw_weight, class: 'form-control', placeholder: "(Grams)" %>
		</div>

		<div class="col-md-4 form-group">
			<%= f.label :Storage_method_of_beans %>
			<%= f.text_field :storage, class: 'form-control' %>
		</div>
	</div>

	<div class="row col-md-12">
	  <%= f.submit 'Create Roast', class: 'btn btn-coffee' %>
	  <%= link_to'Cancel', root_path, class: 'btn btn-coffee2' %>
	</div>
<% end %>


<%# target date_of_roast text_field for Bootstrap datepicker %>
<%= javascript_tag do %>
	$('#timepicker').datetimepicker({format: 'LT'});
	$('#datepicker').datetimepicker({format: 'DD/MM/YYYY'});
<% end %>

app/views/roasts/show.html.erb
<div class='roast-show-wrapper'>
  <div class='left-text'>

    <div>
      <h3>Roast Method:</h3><%= @roast.roast_method %>
    </div>
    <div class='roast-data'>
      <div class='roast-data-col'>
        <div>
          <h3>Date of roast:</h3><%= @roast.roast_date %>
        </div>
        <div>
          <h3>Time of Roast</h3><%= @roast.formattted_time_of_roast %>
        </div>
        <div>
          <h3>Bean Species:</h3><%= @roast.bean_species %>
        </div>
        <div>
          <h3>Bean Country of Origin:</h3><%= @roast.formatted_bean_country_origin %>
        </div>
        <div>
          <h3>Bean Varietal:</h3><%= @roast.formatted_bean_varietal %>
        </div>
      </div>
      <div class='roast-data-col'>
        <div>
          <h3>Roast Duration</h3><%= @roast.formatted_roast_duration %>
        </div>
        <div>
          <h3>Profile:</h3><%= @roast.formatted_roast_profile %>
        </div>
        <div>
          <h3>Average temp during roast:</h3><%= @roast.formatted_avg_temp_roast %>
        </div>
        <div>
          <h3>Raw weight of beans:</h3><%= @roast.formatted_raw_weight %>
        </div>
        <div>
          <h3>Storage Method:</h3><%= @roast.formatted_storage %>
        </div>
      </div>
    </div>

    <div>
      <%= link_to 'All Roasts', root_path, class: 'btn btn-coffee' %>
      <%= link_to "Brews", roast_brews_path(@roast.id), class: 'btn btn-info' %>
      <%= link_to 'Edit', edit_roast_path(@roast.id), class: 'btn btn-coffee2' %>
    </div>
  </div>

  <div class='charts'>
    <%= column_chart @raw_roast.brews.group(:overall).count %>
  </div>
</div>

app/views/shared/_alerts.html.erb
<% flash.each do |name, msg| %>
  <div id='flash' class='alert alert-<%="#{name}"%>'>
    <a href='#' class='close' data-dismiss='alert'>&#215;</a>
    <%= content_tag :div, msg, id: "flash#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

<%# set a time out for 3 seconds to remove the notice div %>
<%= javascript_tag do %>

	setTimeout(function(){
		$('#flash').fadeOut(500);
		$('#flashnotice').empty();
	}, 1500);

<% end %>

app/views/shared/_nav.html.erb
<div class='logo'><h2><%#= controller_name.capitalize %></h2></div>
<ul class="custom-nav nav nav-tabs">

  <li class="active"><%#= link_to'Home', root_path %></li>
  <% if current_user %>
    <li class="dropdown pull-right">
      <a href='#' data-toggle='dropdown' class="dropdown-toggle">
      <span class="glyphicon glyphicon-cog"></span><strong class="caret"></strong></a>
      <ul class='dropdown-menu'>
        <li>
          <img id="fb_picture" src="<%= current_user.picture%>"> 
          <small><%= current_user.nickname %></small>
        </li>
        <li>
          <%= link_to "My Brews", users_path %>
        </li>
        <li class='divider'></li>
        <li>
          <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
        </li>
      </ul>
    </li>
  <% end %>
</ul>